#!/bin/bash

set -e

display_help() {
    echo "usage:"
    echo "  amdpower set          <ryzen|cpu>   <powersave|performance>"
    echo "                        <radeon|gpu>  <powersave|performance>"
    echo "                        all           <powersave|performance>"
    echo "  amdpower get          <radeon|gpu>"
    echo "                        <ryzen|cpu>"
    echo "                        all"
    echo "  amdpower help"
}

cpu() {
    if [ $# -lt 1 ]; then
        echo "must supply <ryzen|cpu> <powersave|performance>"
        exit
    fi

    POWERMODE=$1

    if [ ${POWERMODE} == "performance" ]; then
        for cpu_energy_performance in $(ls /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference); do
            echo 'performance' | doas tee ${cpu_energy_performance}
        done

        for cpu_scaling_governor in $(ls /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor); do
            echo 'performance' | doas tee ${cpu_scaling_governor}
        done

    elif [ ${POWERMODE} == "powersave" ]; then
        for cpu_energy_performance in $(ls /sys/devices/system/cpu/cpu*/cpufreq/energy_performance_preference); do
            echo 'power' | doas tee ${cpu_energy_performance}
        done

        for cpu_scaling_governor in $(ls /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor); do
            echo 'powersave' | doas tee ${cpu_scaling_governor}
        done

    else
        display_help
        exit

    fi

    get cpu
}

gpu() {
    if [ $# -lt 1 ]; then
        echo "must supply <radeon|gpu> <powersave|performance>"
        exit
    fi

    POWERMODE=$1

    if [ ${POWERMODE} == "performance" ]; then
        echo 'auto' | doas tee /sys/class/drm/card1/device/power_dpm_force_performance_level

    elif [ ${POWERMODE} == "powersave" ]; then
        echo 'low' | doas tee /sys/class/drm/card1/device/power_dpm_force_performance_level

    else
        display_help
        exit

    fi

    get gpu
}

setsetting() {
    if [ $# -lt 2 ]; then
        echo "must supply set <gpu|radeon|cpu|ryzen|all> <powersave|performance>"
        exit
    fi

    SYSTEMTOSET=$1

    shift

    if [ ${SYSTEMTOSET} == "cpu" ] || [ ${SYSTEMTOSET} == "ryzen" ]; then
        cpu $@

    elif [ ${SYSTEMTOSET} == "gpu" ] || [ ${SYSTEMTOSET} == "radeon" ]; then
        gpu $@

    elif [ ${SYSTEMTOSET} == "all" ]; then
        cpu $@
        gpu $@

    else
        echo "must supply set with first argument of <gpu|radeon|cpu|ryzen|all>"
        display_help
        exit

    fi
}

get() {
    if [ $# -lt 1 ]; then
        echo "must supply get <gpu|radeon|cpu|ryzen>"
        exit
    fi

    SYSTEMTOGET=$1

    if [ ${SYSTEMTOGET} == "all" ]; then
        get cpu
        get gpu

    elif [ ${SYSTEMTOGET} == "cpu" ] || [ ${SYSTEMTOGET} == "ryzen" ]; then
        echo "CPU status"
        bat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference
        bat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor

    elif [ ${SYSTEMTOGET} == "gpu" ] || [ ${SYSTEMTOGET} == "radeon" ]; then
        echo "GPU status"
        bat /sys/class/drm/card1/device/power_dpm_force_performance_level

    else
        echo "must supply one of 'gpu', 'cpu', or 'all' to <get>"
        display_help
        exit

    fi

}

main() {
    if [ $# -lt 1 ]; then
        display_help
        exit
    fi

    COMMAND=$1

    shift

    if [ ${COMMAND} == "set" ]; then
        setsetting $@

    elif [ ${COMMAND} == "get" ]; then
        get $@

    elif [ ${COMMAND} == "help" ] || [ ${COMMAND} == "-h" ] || [ ${COMMAND} == "--help" ]; then
        display_help
        exit

    else
        echo "unknown command: '${COMMAND}'"
        display_help
        exit
    fi
}

main $@
