#!/bin/bash

set -e

display_help() {
    echo "usage:"
    echo "  brightstepctl up"
    echo "  brightstepctl down"
    echo "  brightstepctl help"
}

function move_brightness() {
    OPERATION=$1

    CURRENT_BRIGHTNESS=$(brightnessctl -m get)

    CONFIG_FILE=~/.config/brightstepctl/config

    if [ $# -eq 3 ]; then
        CONFIG_FILE=$2
    fi

    BRIGHTNESS_TO_SET=$(stepper u32 $OPERATION $CURRENT_BRIGHTNESS $CONFIG_FILE)

    brightnessctl -m set "${BRIGHTNESS_TO_SET}"
}

main() {
    if [ $# -lt 1 ]; then
        display_help
        exit
    fi

    move_brightness $@
}

main $@
