#!/bin/bash

if [ $# -lt 2 ] ; then
    echo 'must supply <SKIP-COUNT> <CMD> <CMD-ARGS>'
    echo '    <SKIP-COUNT> is how many lines to skip as "headers"'
    echo '    <CMD> is the command you want to run'
    echo '    <CMD-ARGS> are the arguments to pass to the command'
fi

# Capture the number of lines that should be counted as header(s)
COUNTER=$1
shift
# Capture entire command passed as command line arguments to this script
CMD=$1
shift
ARGS=$@

# Store the old IFS to reset after capturing the header
OLD_IFS=${IFS}

# Sets IFS (Internal Field Separator) to nothing that all original spaces are preserved
# We want to capture the line as-is and do not wish to change it in any way
IFS=''
# Read first line as the header line to preserve and then print it back out
for (( i = 0 ; i < ${COUNTER} ; i++ ));  do
    read header
    echo $header
done

# Restore the old IFS now that we've captured the header
IFS=${OLD_IFS}

# run the captured command with the rest of standard input
$CMD $ARGS < /dev/stdin
