#!/usr/bin/env python

import sys

def main():
    parts = sys.stdin.read().split('.')
    ones = parts[0].strip()
    tens_and_hundreds = parts[1].strip()
    ret = ""
    if ones != "0":
        ret = ret + ones
    ret = ret + tens_and_hundreds.ljust(2, "0")
    print(ret)

if __name__ == '__main__':
    main()
