#!/usr/bin/env python

import sys
import fractions

def main():
    input_fraction = fractions.Fraction(sys.stdin.read())

    percentage = input_fraction * 100

    print(percentage)

if __name__ == '__main__':
    main()
