#!/bin/bash

echo "CPU:"

cat /proc/cpuinfo  | rg 'model name' | uniq | cut -d ':' -f 2 | xargs | sed 's/^/    /'

echo ""

echo "RAM:"

USEDRAM=$(free --mega | grep "Mem" | awk '{printf("%5.1fG", $3 / 1000)}' | xargs)
TOTALRAM=$(free --mega | grep "Mem" | awk '{printf("%5.1fG", $2 / 1000)}' | xargs)
echo "${USEDRAM} / ${TOTALRAM}" | sed 's/^/    /'

echo ""

echo "GPU:"

glxinfo  | rg "Device" | cut -d ":" -f 2 | cut -d "(" -f 1 | xargs | sed 's/^/    /'

echo ""

echo "Display(s):"

WIDTH=$(swaymsg -t get_outputs | jq '.[0].rect.width')
HEIGHT=$(swaymsg -t get_outputs | jq '.[0].rect.height')
REFRESH=$(swaymsg -t get_outputs | jq '.[0].current_mode.refresh' | python -c 'import sys; print(round(int(sys.stdin.readlines()[0].strip("\n"))/1000))')

echo "${WIDTH}x${HEIGHT} @ ${REFRESH}Hz" | sed 's/^/    /'

echo ""

echo "Audio:"

echo "$(wpctl get-volume @DEFAULT_SINK@ | cut -d ':' -f 2 | percentify)%" | sed 's/^/    /'

echo ""

echo "Internet:"

NETWORKNAME=$(jq ".network_name" ~/.config/wifictl/config.json | tr -d '"')
WIFINETWORK=$(ip -j add | jq ".[] | select(.ifname == \"${NETWORKNAME}\")")

echo "    name:   ${NETWORKNAME}"
echo "    status: $(echo ${WIFINETWORK} | jq .operstate           | tr -d '"')"
echo "    family: $(echo ${WIFINETWORK} | jq .addr_info[0].family | tr -d '"')"
echo "    addr:   $(echo ${WIFINETWORK} | jq .addr_info[0].local  | tr -d '"')"

echo ""

echo "Disk(s):"
df -h | header 2 sort | header 1 rg --color never '^/' | sed 's/^/    /'

echo ""
